##########################################
# Software Engineering 2014 Configuration
##########################################

# Student spreadsheet configuration
spreadsheet:
    title: SwEng 2014 Students
    students_worksheet: Students
    teams_worksheet: Teams

# Github organization configuration
organization:
    name: sweng-epfl-2014
    staff-team-id: 1234567 # Get this from the team URL in the web interface
    class-team-id: 2345678

    homework-team-prefix: "SwEng Team - "
    homework-repo-prefix: "sweng-team-"
    exam-team-prefix: "SwEng Student - "
    exam-repo-prefix: "sweng-student-"

google_auth:
    client_id: 123.apps.googleusercontent.com
    # This should be stored secretly somewhere...
    client_secret: XYZ

github_auth:
    # The note and URL displayed in the Github configuration
    note: SwEng student management
    url: http://sweng.epfl.ch
