##########################################
# Software Engineering 2015 Configuration
##########################################

# Student spreadsheet configuration
spreadsheet:
    title: SwEng Students 2015
    students_worksheet: Students
    teams_worksheet: Teams

# Github organization configuration
organization:
    name: sweng-epfl-2015
    # these are the correct IDs for 2015
    staff-team-id: 1754583
    class-team-id: 1760748

    homework-team-prefix: "SwEng Team - "
    homework-repo-prefix: "sweng-team-"
    exam-team-prefix: "SwEng Student - "
    exam-repo-prefix: "sweng-student-"

google_auth:
    # do this for your own google auth credentials
    client_id: 123.apps.googleusercontent.com
    # This should be stored secretly somewhere...
    client_secret: XYZ

github_auth:
    # The note and URL displayed in the Github configuration
    note: SwEng student management
    url: http://sweng.epfl.ch
